### PR TITLE
update Ajv to 5.0.0

### PR DESCRIPTION
**Pull request by epoberezkin**
All schemas are compatible

### CODE REVIEW

**Comment by epoberezkin** [comment]
If https://github.com/ahmadnassri/har-schema/pull/1 is merged, an additional change can be made here...

**Comment by epoberezkin** [comment]
Updated har-schema. This can be a minor version change (or maybe even a patch - users won't see any difference).

This change will help users who user request package with webpack.

**Comment by epoberezkin** [comment]
@ahmadnassri could you please merge/release it? It will help people who use request in the browser with webpack. See https://github.com/request/request/issues/2652 for example.

Thank you!

**Comment by ahmadnassri** [comment]
i just saw a 5.1 release, should it be updated for that as well?

**Comment by epoberezkin** [comment]
har-validator will pick Ajv 5.1.0 anyway, but I can update if you prefer.

**Pull request merged**
