### PR TITLE
Separate schemas into har-schema

### PR DESCRIPTION
**Pull request by epoberezkin**
I added correct IDs and refs between schemas but is-my-json-valid is still unable to correctly resolve them (ajv can though).
If that's all ok I was thinking to replace the code that replaces refs with subschemas with a more generic code so it is not dependent on the schemas structure.
Let me know if you'd like to move har-schema to your github account.

### CODE REVIEW

**Comment by ahmadnassri** [comment]
looking good, gonna review the `har-schema` repo too

**Comment by epoberezkin** [comment]
Thank you. I also think it may make sense having schema tests to har-schema repo (valid/invalid samples in this format: https://github.com/json-schema-org/JSON-Schema-Test-Suite/tree/develop/tests/draft4), and having code tests here.

**Comment by epoberezkin** [comment]
@ahmadnassri hi, did you have chance to have a look at it?

**Comment by ahmadnassri** [comment]
hey @epoberezkin sorry for the delay, not ignoring this I promise! just a bit of busy time with personal stuff!! 

this is on top of my mind and I will be getting to it soon! as part of a big overhaul of HAR tooling work I wanna do, might even start a "github org" to group all the "har tools" under, more details soon :)

**Pull request closed without merging**
